### ISSUE TITLE
File to import not found or unreadable: active_bootstrap_skin

### ISSUE THREAD

**Issue by jasper502** [vinhnglx/active_bootstrap_skin#2]
Tried it out - no luck right off the bat:

File to import not found or unreadable: active_bootstrap_skin

**Comment by vinhnglx** [comment]
@jasper502 I guess you have to setup the bootstrap-sass gem first. Because the gem require we need to have bootstrap first. Btw, I think the README file is not clear, I'll update right now.

**Comment by jasper502** [comment]
I do have the bootstrap-sass gem installed - I already had it.

**Comment by vinhnglx** [comment]
Did you import the bootstrap in application.css.scss?

@import "bootstrap-sprockets";
@import "bootstrap";

**Comment by vinhnglx** [comment]
Could you show me the full error message in your terminal?

**Comment by jasper502** [comment]
https://gist.github.com/jasper502/26d6aebc8efb48a62625d3f8e5cd963b

**Comment by jasper502** [comment]
I do have those two @imports declared

**Comment by vinhnglx** [comment]
@jasper502 i saw this error, let me check it and fix soon.

**Comment by vinhnglx** [comment]
@jasper502 could you please try again?. I have just fixed this error in PR #3 and release a new version(https://github.com/vinhnglx/active_bootstrap_skin/releases/tag/v0.1.1)  for this hotfix.

**Comment by jasper502** [comment]
ran bundle update (confirmed it bumped to 0.1.1), restarted the server but still have the same error.

**Comment by okliv** [comment]
+1

**Comment by lukasz-wojcik** [comment]
The issue is simple in this case.
when executed `bundle show active_bootstrap_skin` it show the directory where gem is installed.
In there I have seen only `lib` and `bin` folder so no app folder with assets is actually loaded ;)

#6 Fixes that problem

**Comment by vinhnglx** [comment]
@sonar0007 I knew this problem, too. I tried to fix. I'll merge you PR and build again. Thanks so much.

**Comment by vinhnglx** [comment]
@jasper502 could you try again? I merged and release the Sonna007's PR. ( #6 )

**Comment by jasper502** [comment]
All good now - thanks!
